#!/usr/bin/env python3
"""Check the v1 -> v2 migration against Room's own exported schema.

Room validates the migrated database at runtime and throws if anything differs from the
entities, which is what `MigrationV1ToV2Test` relies on. That check is authoritative but it
only reports the *first* table it dislikes, and only when the test runs. This script does the
whole comparison up front and names every discrepancy at once:

    for each table Room expects in schema version 2:
        columns after migration  ==  (v1 columns, if the table existed in v1)
                                     | (columns from a migration CREATE TABLE)
                                     | (columns from migration ALTER TABLE ADD COLUMN)
        indices after migration  ==  (v1 indices) | (indices the migration creates)

Ground truth is `app/schemas/2.json`, generated by Room's annotation processor from the
entities -- not a re-reading of the entity source, so affinity and default values come from
Room itself.

The v1 side is the DDL in `MigrationV1ToV2Test`, which is the only description of schema
version 1 that exists: v1 shipped with `fallbackToDestructiveMigration()` and never exported a
schema. That makes this script a check on the test fixture as much as on the migration, which
is the point -- a fixture that misdescribes v1 produces exactly the failure it is meant to
catch, and did.

Exits 1 on any mismatch. Exits 0 with a notice if the exported schema is absent, since that
means the build was incremental and Room skipped codegen, not that the migration is wrong.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SCHEMA = REPO / "app/schemas/2.json"
MIGRATIONS = REPO / "app/src/main/java/com/warehouse/inventory/data/local/Migrations.kt"
V1_FIXTURE = REPO / "app/src/test/java/com/warehouse/inventory/data/MigrationV1ToV2Test.kt"

# Matches a column line inside a CREATE TABLE body: `name` TYPE ...
COLUMN = re.compile(r"`(\w+)`\s+(?:INTEGER|TEXT|REAL|BLOB|NUMERIC)\b", re.I)


def create_table_blocks(source: str, keyword: str) -> dict[str, str]:
    """Table name -> raw CREATE TABLE body, for every such statement in `source`."""
    blocks: dict[str, str] = {}
    for match in re.finditer(keyword + r"\s+`(\w+)`\s*\(", source, re.I):
        table = match.group(1)
        # Walk to the matching close paren so nested parens (a FK clause) do not end it early.
        depth, i = 1, match.end()
        while i < len(source) and depth:
            if source[i] == "(":
                depth += 1
            elif source[i] == ")":
                depth -= 1
            i += 1
        blocks[table] = source[match.end() : i - 1]
    return blocks


def index_set(source: str) -> set[tuple[str, tuple[str, ...], bool]]:
    """(table, columns, unique) for every CREATE INDEX in `source`.

    Handles Kotlin string concatenation and `$column` interpolation by flattening the source
    first: the migration builds its inventory_transactions indices in a loop, and a naive
    single-statement regex silently misses all seven.
    """
    flat = source.replace('" +', "").replace('"', " ")
    found = set()
    for match in re.finditer(
        r"CREATE\s+(UNIQUE\s+)?INDEX\s+(?:IF\s+NOT\s+EXISTS\s+)?`([^`]+)`\s+ON\s+`(\w+)`\s*\(([^)]*)\)",
        flat,
        re.I,
    ):
        unique = bool(match.group(1))
        table = match.group(3)
        cols = tuple(re.findall(r"`(\w+)`", match.group(4)))
        if cols:
            found.add((table, cols, unique))
    # The loop-built indices carry a `$column` placeholder in both the name and the column
    # list; expand the literal list the migration iterates over.
    loop = re.search(
        r"listOf\(\s*((?:\s*\"[\w]+\"\s*,?\s*)+)\)\s*\.forEach\s*\{\s*column",
        source,
    )
    if loop and "index_inventory_transactions_" in source:
        for col in re.findall(r'"(\w+)"', loop.group(1)):
            found.add(("inventory_transactions", (col,), False))
    return found


def main() -> int:
    if not SCHEMA.exists():
        print(f"NOTICE: {SCHEMA.relative_to(REPO)} not present -- incremental build, "
              "Room skipped codegen. Nothing to compare.")
        return 0

    schema = json.loads(SCHEMA.read_text(encoding="utf-8"))["database"]
    version = schema["version"]
    migration_src = MIGRATIONS.read_text(encoding="utf-8")
    fixture_src = V1_FIXTURE.read_text(encoding="utf-8")

    v1_tables = {t: set(COLUMN.findall(b)) for t, b in
                 create_table_blocks(fixture_src, "CREATE TABLE").items()}
    mig_tables = {t: set(COLUMN.findall(b)) for t, b in
                  create_table_blocks(migration_src, "CREATE TABLE IF NOT EXISTS").items()}
    for m in re.finditer(r"ALTER TABLE `(\w+)` ADD COLUMN `(\w+)`", migration_src):
        mig_tables.setdefault(m.group(1), set()).add(m.group(2))

    all_indices = index_set(migration_src) | index_set(fixture_src)

    print(f"Room exported schema version {version}; "
          f"{len(schema['entities'])} entities to satisfy.\n")
    print(f"{'table':26s} {'columns':>9s}  {'indices':>8s}  verdict")
    print("-" * 62)

    failures: list[str] = []
    for entity in sorted(schema["entities"], key=lambda e: e["tableName"]):
        table = entity["tableName"]
        expected_cols = {f["columnName"] for f in entity["fields"]}
        expected_idx = {
            (table, tuple(i["columnNames"]), bool(i.get("unique")))
            for i in entity.get("indices", [])
        }

        actual_cols = v1_tables.get(table, set()) | mig_tables.get(table, set())
        problems = []
        if not actual_cols:
            problems.append("table never created")
        else:
            missing = expected_cols - actual_cols
            extra = actual_cols - expected_cols
            if missing:
                problems.append(f"missing column(s) {sorted(missing)}")
            if extra:
                problems.append(f"unexpected column(s) {sorted(extra)}")

        missing_idx = expected_idx - all_indices
        if missing_idx:
            problems.append(
                "missing index/indices "
                + str(sorted((cols, "unique" if u else "plain") for _, cols, u in missing_idx))
            )

        verdict = "OK" if not problems else "MISMATCH"
        print(f"{table:26s} {len(expected_cols):9d}  {len(expected_idx):8d}  {verdict}")
        for problem in problems:
            print(f"{'':26s} {'':9s}  {'':8s}    - {problem}")
            failures.append(f"{table}: {problem}")

    print()
    if failures:
        print(f"FAIL: {len(failures)} discrepancy/discrepancies between the migration "
              "and Room's exported schema.")
        return 1
    print("PASS: every table Room expects in v2 is produced with the right columns "
          "and indices.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
